config/routes.rb
ReadyBlog::Application.routes.draw do
  devise_for :users

  root to: 'pages#landing'

  resources :posts

  resources :users do
    resources :posts
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  attr_accessible :body, :title, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name
  # attr_accessible :title, :body

  validates_presence_of :first_name, :last_name

  has_many :posts

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = current_user.posts.new
  end

  def show
    @post = Post.find(params[:id])    
  end

  def create
    @post = current_user.posts.new(params[:post])
    if @post.save
      redirect_to root_path
    else
      render action: 'new'
    end
  end

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def update
    @post = Post.find(params[:id])
    @post.published = params[:published] == "1"
    @post.save
    redirect_to user_posts_path(current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index 
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ReadyBlog
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    #page
      .header
        #logo= link_to 'Ready Blog', root_path
        = render 'shared/site_nav'

        - if user_signed_in?
          = link_to 'Sign Out',
            destroy_user_session_path,
            id: 'sign_out_link',
            method: 'delete'


      %p.notice= notice
      %p.alert= alert

      .center
        = yield

      .footer

app/views/pages/landing.html.haml
.intro Welcome to ReadyBlog!

  
- if !user_signed_in?
  .landing_forms
    #sign_in_form
      %h2 SIGN IN
      = simple_form_for(:user, :url => new_user_session_path) do |f|
        = f.input :email
        = f.input :password
        = f.button :submit, 'Sign In'

      = link_to "Forgot your password?", new_user_password_path

    #sign_up_form
      %h2 SIGN UP
      = simple_form_for(User.new, :url => user_registration_path) do |f|
        = f.input :first_name
        = f.input :last_name
        = f.input :email
        = f.input :password
        = f.input :password_confirmation
        = f.button :submit, 'Sign Up'

app/views/posts/index.html.haml
- @posts.each do |post|
  .post
    %h2 #{post.title}
    %p #{post.body}
    = link_to t('posts.show'), post_path(post)
  .post_status
    - if post.published
      %p This post is published.
    - else
      = link_to('Publish This Post', post_path(post, published: 1), method: :put, confirm: 'Are you sure?')

app/views/posts/new.html.haml
= simple_form_for(@post) do |f|
  = f.hidden_field :user_id, value: current_user.id
  = f.input :title, label: t('posts.form_labels.title')
  = f.input :body
  = f.submit 'Create Post'

app/views/posts/show.html.haml
.post_content
  %h2 #{@post.title}
  %p #{@post.body}
.post_status
  - if @post.published
    %p This post is published
  - else
    = link_to('Publish This Post', post_path(@post, published: 1), method: :put, confirm: 'Are you sure?')

app/views/shared/_site_nav.html.haml
%nav
  = link_to t('users.index'), users_path

  - if user_signed_in?

    = link_to t('posts.new'), new_post_path
    = link_to t('posts.browse'), user_posts_path(current_user)

app/views/users/index.html.haml
- @users.each do|user|
  .user
    = link_to user.full_name, user_posts_path(user)